---
name: Post-Release

on:
  push:
    tags:
      - '*'

jobs:
  post-release:
    name: Post-Release
    runs-on: ubuntu-latest
    steps:
      - name: Print version number
        run: "echo \"Version: ${{ github.ref_name }}\""
